### ISSUE TITLE
NoSuchMethodError when launching from GreenPepper runner

### ISSUE THREAD

**Issue by arnor2000** [strator-dev/greenpepper#24]
`commons-codec-1.3` embedded in `greenpepper-maven-runner-2.7-complete.jar` prevents from using any more recent features of Apache commons-codec library.

For example the use of `Base64.encodeBase64String()` method introduce in `commons-codec-1.4` result in following error : 
```
Caused by: java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;
	at com.strator.iris.commande.communication.logistadis.service.CommandeRestTemplateBuilder.init(CommandeRestTemplateBuilder.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:344)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:295)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:130)
	... 104 more
```

**Comment by wattazoum** [comment]
I think that the problem could be solved by using maven-shade-plugin instead of maven-assembly.

**Comment by wattazoum** [comment]
Here is a test project that shows the problem
[test-issue24.zip](https://github.com/strator-dev/greenpepper/files/79654/test-issue24.zip)
