### ISSUE TITLE
Some runner thread might die when there is a global exception

### ISSUE THREAD

**Issue by wattazoum** [strator-dev/greenpepper#60]
In the STD ERR

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
An unexpected error occured
java.lang.NullPointerException
    at com.greenpepper.interpreter.ListOfInterpreter.execute(ListOfInterpreter.java:105)
    at com.greenpepper.interpreter.collection.CollectionInterpreter.interpret(CollectionInterpreter.java:289)
    at com.greenpepper.document.Document.execute(Document.java:169)
    at com.greenpepper.interpreter.flow.dowith.InterpretRow.interpret(InterpretRow.java:68)
    at com.greenpepper.interpreter.flow.AbstractFlowInterpreter.execute(AbstractFlowInterpreter.java:90)
    at com.greenpepper.interpreter.flow.AbstractFlowInterpreter.interpret(AbstractFlowInterpreter.java:44)
    at com.greenpepper.document.Document.execute(Document.java:169)
    at com.greenpepper.runner.DocumentRunner.run(DocumentRunner.java:156)
    at com.greenpepper.runner.CommandLineRunner.runSpec(CommandLineRunner.java:120)
    at com.greenpepper.runner.CommandLineRunner.run(CommandLineRunner.java:107)
    at com.greenpepper.runner.Main.main(Main.java:46)
```

There is a resulting xml here:

``` xml
<documents>
<global-exception>
<![CDATA[
java.lang.NullPointerException com.greenpepper.interpreter.ListOfInterpreter.execute(ListOfInterpreter.java:105) com.greenpepper.interpreter.collection.CollectionInterpreter.interpret(CollectionInterpreter.java:289) 
com.greenpepper.document.Document.execute(Document.java:169) 
com.greenpepper.interpreter.flow.dowith.InterpretRow.interpret(InterpretRow.java:68) 
com.greenpepper.interpreter.flow.AbstractFlowInterpreter.execute(AbstractFlowInterpreter.java:90) 
com.greenpepper.interpreter.flow.AbstractFlowInterpreter.interpret(AbstractFlowInterpreter.java:44) 
com.greenpepper.document.Document.execute(Document.java:169) 
com.greenpepper.runner.DocumentRunner.run(DocumentRunner.java:156) 
com.greenpepper.runner.CommandLineRunner.runSpec(CommandLineRunner.java:120) 
com.greenpepper.runner.CommandLineRunner.run(CommandLineRunner.java:107) 
com.greenpepper.runner.Main.main(Main.java:46)
]]>
</global-exception>
</documents>
```

**Comment by wattazoum** [comment]
I couldn't reproduce. A ticket will be created in case it comes back.
